sudo: false
dist: trusty
language: c++
compiler: clang-3.6

addons:
  apt:
    update: on
    sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
    packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - libenet-dev
    - libgtk-3-dev
    - g++-4.9
    - clang-3.6

before_script:
- mkdir build && cd build
- cmake .. -G"Unix Makefiles"

script:
- sudo cmake --build .

notifications:
  email: false
